{
 "title": "Time Series re:Invent demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "All CEPs detected",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "measure": "avg_temperature",
     "rawQuery": "SELECT bin(time, $__interval_ms) as time_interval, sensor_id, history, \n        MAX(CASE WHEN measure_name = 'avg_temperature' THEN measure_value::double ELSE NULL END)\n     AS avg_temperature,\n        MAX(CASE WHEN measure_name = 'elapsed' THEN measure_value::double ELSE NULL END)\n     AS elapsed\nFROM  $__database.$__table\n        WHERE $__timeFilter\n        group by bin(time, $__interval_ms), sensor_id, history\n       "
    }
   ]
  },
  {
   "title": "CEPs over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "measure": "max_temperature",
     "rawQuery": "SELECT time, measure_value::double as max_temperature\nFROM  $__database.$__table\n        WHERE $__timeFilter and measure_name = '$__measure'"
    }
   ]
  },
  {
   "title": "Temperature readings",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawQuery": "SELECT * FROM $__database.$__table WHERE $__timeFilter order by time\n\n\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "CountByStatus",
   "type": "stat",
   "description": "Count the number of hosts per micro-service in a specific region.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measure": "temperature",
     "rawQuery": "SELECT CASE WHEN status = 'OK' THEN total ELSE NULL END AS STATUS_OK,\n       CASE WHEN status = 'WARNING' THEN total ELSE NULL END AS STATUS_WARNING,\n       CASE WHEN status = 'ERROR' THEN total ELSE NULL END AS STATUS_ERROR\nFROM (       \n        SELECT status, COUNT(*) as total\n        FROM $__database.$__table\n        WHERE $__timeFilter\n            AND measure_name = '$__measure'           \n        GROUP BY status\n    )\n    "
    }
   ]
  },
  {
   "title": "global percentiles for temp every 30secs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measure": "temperature",
     "rawQuery": "SELECT BIN(time, 30s) AS time_bin,\n    ROUND(AVG(measure_value::double), 2) AS avg_value,\n    ROUND(APPROX_PERCENTILE(measure_value::double, 0.9), 2) AS p90_value,\n    ROUND(APPROX_PERCENTILE(measure_value::double, 0.75), 2) AS p75_value\nFROM $__database.$__table\nWHERE $__timeFilter\n    AND measure_name = '$__measure'   \nGROUP BY BIN(time, 30s)  \nORDER BY time_bin desc\n"
    }
   ]
  },
  {
   "title": "MAX temperature in past 10 seconds",
   "type": "table",
   "gridPos": { "h": 48, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "measure": "temperature",
     "rawQuery": "SELECT sensor_id, BIN(time,10s) as time, \n    MAX(measure_value::double) as latest_temperature\nFROM $__database.$__table\nWHERE time between ago(10s) and now() \n    AND measure_name = '$__measure'       \nGROUP BY sensor_id, BIN(time,10s) \nORDER BY latest_temperature desc"
    }
   ]
  },
  {
   "title": "All sensors MAX temperatures in interval",
   "type": "table",
   "gridPos": { "h": 48, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "measure": "temperature",
     "rawQuery": "SELECT sensor_id, \n    MAX(measure_value::double) as latest_temperature\nFROM $__database.$__table\nWHERE $__timeFilter\n    AND measure_name = '$__measure'       \nGROUP BY sensor_id \nORDER BY latest_temperature desc"
    }
   ]
  }
 ]
}